server:
  port: 8081  # Puerto en el que correrá tu aplicación

spring:
  r2dbc:
    url: r2dbc:postgresql://ep-odd-lab-a8v74ax4-pooler.eastus2.azure.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_lmMFHLYVCa26
    properties:
      ssl: true
  sql:
    init:
      mode: always  # Para inicializar la BD con scripts si es necesario
  logging:
    level:
      org.springframework.r2dbc: DEBUG  # Para ver logs de R2DBC


# Comandos para ejecutar
# sdk install java 17.0.11-jbr
# mvn clean install -DskipTests
# mvn spring-boot:run

# URL alternativa para la conexión JDBC
# jdbc:postgresql://ep-odd-lab-a8v74ax4-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_lmMFHLYVCa26&sslmode=require
